export default {
  nav: {
    overview: 'Resumen', inventory: 'Inventario', orders: 'Pedidos',
    finance: 'Finanzas', demandForecast: 'Previsión de Demanda',
    reports: 'Informes', restocking: 'Reabastecimiento',
    companyName: 'Catalyst Components', subtitle: 'Sistema de Gestión de Inventario'
  },
  dashboard: {
    title: 'Resumen',
    kpi: { title: 'Indicadores Clave de Rendimiento', inventoryTurnover: 'Rotación de Inventario', ordersFulfilled: 'Pedidos Cumplidos', orderFillRate: 'Tasa de Cumplimiento', revenue: 'Ingresos (Pedidos)', revenueYTD: 'Ingresos YTD', revenueMTD: 'Ingresos MTD', avgProcessingTime: 'Tiempo Medio de Proceso (Días)', goal: 'Objetivo' },
    summary: { title: 'Resumen' },
    orderHealth: { title: 'Estado de Pedidos', totalOrders: 'Total Pedidos', revenue: 'Ingresos', avgOrderValue: 'Valor Medio del Pedido', onTimeRate: 'Tasa Puntualidad', avgFulfillmentDays: 'Días Medios de Cumplimiento', total: 'Total' },
    ordersByMonth: { title: 'Pedidos por Mes' },
    inventoryValue: { title: 'Valor de Inventario por Categoría' },
    inventoryShortages: { title: 'Escasez de Inventario', noShortages: 'Sin escasez - ¡todos los pedidos pueden cumplirse!', noData: 'Sin datos para los filtros seleccionados', orderId: 'ID Pedido', sku: 'SKU', itemName: 'Nombre Artículo', quantityNeeded: 'Cantidad Necesaria', quantityAvailable: 'Cantidad Disponible', shortage: 'Escasez', daysDelayed: 'Días de Retraso', priority: 'Prioridad', unitsShort: 'unidades faltantes', days: 'días' },
    topProducts: { title: 'Productos Principales por Ingresos', sku: 'SKU', product: 'Producto', category: 'Categoría', warehouse: 'Almacén', stockStatus: 'Estado Stock', revenue: 'Ingresos', unitsOrdered: 'Unidades Pedidas', firstOrder: 'Primer Pedido', inStock: 'En Stock', lowStock: 'Stock Bajo' }
  },
  inventory: { title: 'Inventario', description: 'Gestiona y monitorea todos los artículos', stockLevels: 'Niveles de Stock', skus: 'SKU', searchPlaceholder: 'Buscar por nombre...', clearSearch: 'Limpiar búsqueda', totalItems: 'Total Artículos', totalValue: 'Valor Total', lowStockItems: 'Artículos con Stock Bajo', warehouses: 'Almacenes', table: { sku: 'SKU', itemName: 'Nombre Artículo', name: 'Nombre', category: 'Categoría', warehouse: 'Almacén', quantity: 'Cantidad', quantityOnHand: 'Cantidad en Mano', reorderPoint: 'Punto de Reorden', unitCost: 'Costo Unitario', unitPrice: 'Precio Unitario', totalValue: 'Valor Total', location: 'Ubicación', status: 'Estado' } },
  orders: { title: 'Pedidos', description: 'Ver y gestionar pedidos de clientes', allOrders: 'Todos los Pedidos', totalOrders: 'Total Pedidos', totalRevenue: 'Ingresos Totales', avgOrderValue: 'Valor Medio Pedido', onTimeDelivery: 'Entrega Puntual', itemsCount: '{count} artículos', quantity: 'Cant', table: { orderNumber: 'Número Pedido', orderId: 'ID Pedido', orderDate: 'Fecha Pedido', date: 'Fecha', customer: 'Cliente', category: 'Categoría', warehouse: 'Almacén', items: 'Artículos', value: 'Valor', totalValue: 'Valor Total', status: 'Estado', expectedDelivery: 'Entrega Prevista', actualDelivery: 'Entrega Real' } },
  finance: { title: 'Panel Financiero', description: 'Controla ingresos, costos y rendimiento financiero', totalRevenue: 'Ingresos Totales', totalCosts: 'Costos Totales', netProfit: 'Beneficio Neto', avgOrderValue: 'Valor Medio Pedido', fromOrders: 'De {count} pedidos', costBreakdown: 'Aprovisionamiento + Operativo + Personal + Gastos Generales', margin: 'margen', perOrderRevenue: 'Ingreso por pedido', revenueVsCosts: { title: 'Ingresos vs Costos Mensuales', revenue: 'Ingresos', costs: 'Costos Totales' }, monthlyCostFlow: { title: 'Flujo de Costos Mensual', procurement: 'Aprovisionamiento', operational: 'Operativo', labor: 'Personal', overhead: 'Gastos Generales' }, categorySpending: { title: 'Gasto por Categoría', ofTotal: 'del total' }, transactions: { title: 'Transacciones Recientes', id: 'ID', description: 'Descripción', vendor: 'Proveedor', date: 'Fecha', amount: 'Importe' } },
  demand: { title: 'Previsión de Demanda', description: 'Analiza tendencias y previsiones de demanda', increasingDemand: 'Demanda Creciente', stableDemand: 'Demanda Estable', decreasingDemand: 'Demanda Decreciente', itemsCount: '{count} artículos', more: 'más...', demandForecasts: 'Previsiones de Demanda', table: { sku: 'SKU', itemName: 'Nombre Artículo', currentDemand: 'Demanda Actual', forecastedDemand: 'Demanda Prevista', change: 'Cambio', trend: 'Tendencia', period: 'Período' } },
  reports: { title: 'Informes de Rendimiento', description: 'Métricas trimestrales y tendencias mensuales', quarterlyPerformance: 'Rendimiento Trimestral', monthlyRevenueTrend: 'Tendencia Ingresos Mensual', monthOverMonth: 'Análisis Mes a Mes', totalRevenueYTD: 'Ingresos Totales (YTD)', avgMonthlyRevenue: 'Ingresos Medios Mensuales', totalOrdersYTD: 'Total Pedidos (YTD)', bestQuarter: 'Mejor Trimestre', table: { quarter: 'Trimestre', totalOrders: 'Total Pedidos', totalRevenue: 'Ingresos Totales', avgOrderValue: 'Valor Medio Pedido', fulfillmentRate: 'Tasa Cumplimiento', month: 'Mes', orders: 'Pedidos', revenue: 'Ingresos', change: 'Cambio', growthRate: 'Tasa de Crecimiento' } },
  restocking: { title: 'Recomendaciones de Reabastecimiento', description: 'Recomendaciones de pedidos basadas en stock, previsiones y presupuesto', budgetCeiling: 'Límite de Presupuesto', totalEstimatedSpend: 'Gasto Estimado Total', remainingBudget: 'Presupuesto Restante', itemsCovered: 'Artículos Cubiertos', recommendedOrders: 'Pedidos Recomendados', noRestocking: 'No se necesita reabastecimiento', noRestockingBudget: 'Sin reabastecimiento en el presupuesto actual', allStocked: 'Todos los artículos tienen stock adecuado.', partial: 'parcial', table: { priority: 'Prioridad', sku: 'SKU', product: 'Producto', warehouse: 'Almacén', onHand: 'En Mano', reorderPoint: 'Punto Reorden', forecastedDemand: 'Demanda Prevista', recommendedQty: 'Cant. Recomendada', estimatedCost: 'Costo Estimado', totalEstimatedSpend: 'Gasto Estimado Total' } },
  filters: { timePeriod: 'Período', location: 'Ubicación', category: 'Categoría', orderStatus: 'Estado Pedido', all: 'Todos', allMonths: 'Todos los Meses' },
  status: { delivered: 'Entregado', shipped: 'Enviado', processing: 'En Proceso', backordered: 'Pedido Pendiente', inStock: 'En Stock', lowStock: 'Stock Bajo', adequate: 'Adecuado' },
  trends: { increasing: 'creciente', stable: 'estable', decreasing: 'decreciente' },
  priority: { high: 'Alta', medium: 'Media', low: 'Baja' },
  categories: { circuitBoards: 'Placas de Circuito', sensors: 'Sensores', actuators: 'Actuadores', controllers: 'Controladores', powerSupplies: 'Fuentes de Alimentación' },
  spendingCategories: { rawMaterials: 'Materias Primas', components: 'Componentes', equipment: 'Equipos', consumables: 'Consumibles' },
  warehouses: { sanFrancisco: 'San Francisco', london: 'Londres', tokyo: 'Tokio' },
  months: { jan: 'Ene', feb: 'Feb', mar: 'Mar', apr: 'Abr', may: 'May', jun: 'Jun', jul: 'Jul', aug: 'Ago', sep: 'Sep', oct: 'Oct', nov: 'Nov', dec: 'Dic', january: 'Enero', february: 'Febrero', march: 'Marzo', april: 'Abril', june: 'Junio', july: 'Julio', august: 'Agosto', september: 'Septiembre', october: 'Octubre', november: 'Noviembre', december: 'Diciembre' },
  profile: { profileDetails: 'Detalles del Perfil', myTasks: 'Mis Tareas', logout: 'Cerrar Sesión' },
  profileDetails: { title: 'Detalles del Perfil', email: 'Correo', department: 'Departamento', location: 'Ubicación', phone: 'Teléfono', joinDate: 'Fecha de Ingreso', employeeId: 'ID Empleado', close: 'Cerrar' },
  tasks: { title: 'Mis Tareas', taskTitle: 'Título Tarea', taskTitlePlaceholder: 'Ingresa el título...', priority: 'Prioridad', dueDate: 'Fecha Límite', addTask: 'Agregar Tarea', noTasks: 'Sin tareas. ¡Agrega una arriba!' },
  language: { english: 'English', japanese: '日本語', selectLanguage: 'Seleccionar Idioma' },
  common: { loading: 'Cargando...', error: 'Error', noData: 'Sin datos disponibles', viewDetails: 'Ver Detalles', close: 'Cerrar', save: 'Guardar', cancel: 'Cancelar', search: 'Buscar', filter: 'Filtrar', export: 'Exportar', items: 'artículos' },
  productNames: {},
  customerNames: {}
}
