export default {
  nav: {
    overview: 'Aperçu', inventory: 'Inventaire', orders: 'Commandes',
    finance: 'Finance', demandForecast: 'Prévision de Demande',
    reports: 'Rapports', restocking: 'Réapprovisionnement',
    companyName: 'Catalyst Components', subtitle: 'Système de Gestion des Stocks'
  },
  dashboard: {
    title: 'Aperçu',
    kpi: { title: 'Indicateurs Clés de Performance', inventoryTurnover: 'Rotation des Stocks', ordersFulfilled: 'Commandes Traitées', orderFillRate: 'Taux de Traitement', revenue: 'Revenus (Commandes)', revenueYTD: 'Revenus Cumul Annuel', revenueMTD: 'Revenus du Mois', avgProcessingTime: 'Délai Moyen de Traitement (Jours)', goal: 'Objectif' },
    summary: { title: 'Résumé' },
    orderHealth: { title: 'État des Commandes', totalOrders: 'Total Commandes', revenue: 'Revenus', avgOrderValue: 'Valeur Moyenne Commande', onTimeRate: 'Taux de Ponctualité', avgFulfillmentDays: 'Jours Moyens de Livraison', total: 'Total' },
    ordersByMonth: { title: 'Commandes par Mois' },
    inventoryValue: { title: 'Valeur des Stocks par Catégorie' },
    inventoryShortages: { title: 'Ruptures de Stock', noShortages: 'Aucune rupture - toutes les commandes peuvent être traitées !', noData: 'Aucune donnée pour les filtres sélectionnés', orderId: 'ID Commande', sku: 'SKU', itemName: "Nom de l'Article", quantityNeeded: 'Quantité Nécessaire', quantityAvailable: 'Quantité Disponible', shortage: 'Rupture', daysDelayed: 'Jours de Retard', priority: 'Priorité', unitsShort: 'unités manquantes', days: 'jours' },
    topProducts: { title: 'Produits Principaux par Revenu', sku: 'SKU', product: 'Produit', category: 'Catégorie', warehouse: 'Entrepôt', stockStatus: 'État du Stock', revenue: 'Revenus', unitsOrdered: 'Unités Commandées', firstOrder: 'Première Commande', inStock: 'En Stock', lowStock: 'Stock Faible' }
  },
  inventory: { title: 'Inventaire', description: 'Gérer et suivre tous les articles', stockLevels: 'Niveaux de Stock', skus: 'SKU', searchPlaceholder: "Rechercher par nom d'article...", clearSearch: 'Effacer la recherche', totalItems: 'Total Articles', totalValue: 'Valeur Totale', lowStockItems: 'Articles en Stock Faible', warehouses: 'Entrepôts', table: { sku: 'SKU', itemName: "Nom de l'Article", name: 'Nom', category: 'Catégorie', warehouse: 'Entrepôt', quantity: 'Quantité', quantityOnHand: 'Quantité en Main', reorderPoint: 'Point de Réapprovisionnement', unitCost: 'Coût Unitaire', unitPrice: 'Prix Unitaire', totalValue: 'Valeur Totale', location: 'Emplacement', status: 'Statut' } },
  orders: { title: 'Commandes', description: 'Afficher et gérer les commandes clients', allOrders: 'Toutes les Commandes', totalOrders: 'Total Commandes', totalRevenue: 'Revenus Totaux', avgOrderValue: 'Valeur Moyenne Commande', onTimeDelivery: 'Livraison à Temps', itemsCount: '{count} articles', quantity: 'Qté', table: { orderNumber: 'Numéro Commande', orderId: 'ID Commande', orderDate: 'Date Commande', date: 'Date', customer: 'Client', category: 'Catégorie', warehouse: 'Entrepôt', items: 'Articles', value: 'Valeur', totalValue: 'Valeur Totale', status: 'Statut', expectedDelivery: 'Livraison Prévue', actualDelivery: 'Livraison Réelle' } },
  finance: { title: 'Tableau de Bord Financier', description: 'Suivre les revenus, coûts et performance financière', totalRevenue: 'Revenus Totaux', totalCosts: 'Coûts Totaux', netProfit: 'Bénéfice Net', avgOrderValue: 'Valeur Moyenne Commande', fromOrders: 'De {count} commandes', costBreakdown: 'Approvisionnement + Opérationnel + Main-d\'œuvre + Frais Généraux', margin: 'marge', perOrderRevenue: 'Revenu par commande', revenueVsCosts: { title: 'Revenus vs Coûts Mensuels', revenue: 'Revenus', costs: 'Coûts Totaux' }, monthlyCostFlow: { title: 'Flux de Coûts Mensuel', procurement: 'Approvisionnement', operational: 'Opérationnel', labor: "Main-d'œuvre", overhead: 'Frais Généraux' }, categorySpending: { title: 'Dépenses par Catégorie', ofTotal: 'du total' }, transactions: { title: 'Transactions Récentes', id: 'ID', description: 'Description', vendor: 'Fournisseur', date: 'Date', amount: 'Montant' } },
  demand: { title: 'Prévision de Demande', description: 'Analyser les tendances et prévisions de demande', increasingDemand: 'Demande Croissante', stableDemand: 'Demande Stable', decreasingDemand: 'Demande Décroissante', itemsCount: '{count} articles', more: 'plus...', demandForecasts: 'Prévisions de Demande', table: { sku: 'SKU', itemName: "Nom de l'Article", currentDemand: 'Demande Actuelle', forecastedDemand: 'Demande Prévue', change: 'Variation', trend: 'Tendance', period: 'Période' } },
  reports: { title: 'Rapports de Performance', description: 'Métriques trimestrielles et tendances mensuelles', quarterlyPerformance: 'Performance Trimestrielle', monthlyRevenueTrend: 'Tendance des Revenus Mensuels', monthOverMonth: 'Analyse Mois par Mois', totalRevenueYTD: 'Revenus Totaux (Cumul)', avgMonthlyRevenue: 'Revenus Mensuels Moyens', totalOrdersYTD: 'Total Commandes (Cumul)', bestQuarter: 'Meilleur Trimestre', table: { quarter: 'Trimestre', totalOrders: 'Total Commandes', totalRevenue: 'Revenus Totaux', avgOrderValue: 'Valeur Moyenne Commande', fulfillmentRate: 'Taux de Traitement', month: 'Mois', orders: 'Commandes', revenue: 'Revenus', change: 'Variation', growthRate: 'Taux de Croissance' } },
  restocking: { title: 'Recommandations de Réapprovisionnement', description: 'Recommandations de commandes basées sur le stock, les prévisions et le budget', budgetCeiling: 'Plafond Budgétaire', totalEstimatedSpend: 'Dépense Estimée Totale', remainingBudget: 'Budget Restant', itemsCovered: 'Articles Couverts', recommendedOrders: 'Commandes Recommandées', noRestocking: 'Aucun réapprovisionnement nécessaire', noRestockingBudget: 'Aucun réapprovisionnement dans le budget actuel', allStocked: 'Tous les articles ont un stock adéquat.', partial: 'partiel', table: { priority: 'Priorité', sku: 'SKU', product: 'Produit', warehouse: 'Entrepôt', onHand: 'En Main', reorderPoint: 'Point Réappro.', forecastedDemand: 'Demande Prévue', recommendedQty: 'Qté Recommandée', estimatedCost: 'Coût Estimé', totalEstimatedSpend: 'Dépense Estimée Totale' } },
  filters: { timePeriod: 'Période', location: 'Emplacement', category: 'Catégorie', orderStatus: 'Statut Commande', all: 'Tous', allMonths: 'Tous les Mois' },
  status: { delivered: 'Livré', shipped: 'Expédié', processing: 'En Cours', backordered: 'En Rupture', inStock: 'En Stock', lowStock: 'Stock Faible', adequate: 'Adéquat' },
  trends: { increasing: 'croissant', stable: 'stable', decreasing: 'décroissant' },
  priority: { high: 'Haute', medium: 'Moyenne', low: 'Basse' },
  categories: { circuitBoards: 'Circuits Imprimés', sensors: 'Capteurs', actuators: 'Actionneurs', controllers: 'Contrôleurs', powerSupplies: "Alimentations" },
  spendingCategories: { rawMaterials: 'Matières Premières', components: 'Composants', equipment: 'Équipements', consumables: 'Consommables' },
  warehouses: { sanFrancisco: 'San Francisco', london: 'Londres', tokyo: 'Tokyo' },
  months: { jan: 'Jan', feb: 'Fév', mar: 'Mar', apr: 'Avr', may: 'Mai', jun: 'Juin', jul: 'Juil', aug: 'Août', sep: 'Sep', oct: 'Oct', nov: 'Nov', dec: 'Déc', january: 'Janvier', february: 'Février', march: 'Mars', april: 'Avril', june: 'Juin', july: 'Juillet', august: 'Août', september: 'Septembre', october: 'Octobre', november: 'Novembre', december: 'Décembre' },
  profile: { profileDetails: 'Détails du Profil', myTasks: 'Mes Tâches', logout: 'Déconnexion' },
  profileDetails: { title: 'Détails du Profil', email: 'Email', department: 'Département', location: 'Emplacement', phone: 'Téléphone', joinDate: "Date d'Embauche", employeeId: 'ID Employé', close: 'Fermer' },
  tasks: { title: 'Mes Tâches', taskTitle: 'Titre de la Tâche', taskTitlePlaceholder: 'Entrez le titre...', priority: 'Priorité', dueDate: 'Date Limite', addTask: 'Ajouter une Tâche', noTasks: 'Aucune tâche. Ajoutez-en une ci-dessus !' },
  language: { english: 'English', japanese: '日本語', selectLanguage: 'Sélectionner la Langue' },
  common: { loading: 'Chargement...', error: 'Erreur', noData: 'Aucune donnée disponible', viewDetails: 'Voir les Détails', close: 'Fermer', save: 'Enregistrer', cancel: 'Annuler', search: 'Rechercher', filter: 'Filtrer', export: 'Exporter', items: 'articles' },
  productNames: {},
  customerNames: {}
}
