export default {
  nav: {
    overview: 'Panoramica', inventory: 'Inventario', orders: 'Ordini',
    finance: 'Finanza', demandForecast: 'Previsione Domanda',
    reports: 'Report', restocking: 'Rifornimento',
    companyName: 'Catalyst Components', subtitle: 'Sistema di Gestione Inventario'
  },
  dashboard: {
    title: 'Panoramica',
    kpi: { title: 'Indicatori Chiave di Performance', inventoryTurnover: 'Rotazione Inventario', ordersFulfilled: 'Ordini Evasi', orderFillRate: 'Tasso Evasione Ordini', revenue: 'Ricavi (Ordini)', revenueYTD: 'Ricavi YTD', revenueMTD: 'Ricavi MTD', avgProcessingTime: 'Tempo Medio Elaborazione (Giorni)', goal: 'Obiettivo' },
    summary: { title: 'Riepilogo' },
    orderHealth: { title: 'Stato Ordini', totalOrders: 'Ordini Totali', revenue: 'Ricavi', avgOrderValue: 'Valore Medio Ordine', onTimeRate: 'Tasso Puntualità', avgFulfillmentDays: 'Giorni Medi Evasione', total: 'Totale' },
    ordersByMonth: { title: 'Ordini per Mese' },
    inventoryValue: { title: 'Valore Inventario per Categoria' },
    inventoryShortages: { title: 'Carenze Inventario', noShortages: 'Nessuna carenza - tutti gli ordini possono essere evasi!', noData: 'Nessun dato per i filtri selezionati', orderId: 'ID Ordine', sku: 'SKU', itemName: 'Nome Articolo', quantityNeeded: 'Quantità Necessaria', quantityAvailable: 'Quantità Disponibile', shortage: 'Carenza', daysDelayed: 'Giorni di Ritardo', priority: 'Priorità', unitsShort: 'unità mancanti', days: 'giorni' },
    topProducts: { title: 'Prodotti Principali per Ricavo', sku: 'SKU', product: 'Prodotto', category: 'Categoria', warehouse: 'Magazzino', stockStatus: 'Stato Stock', revenue: 'Ricavi', unitsOrdered: 'Unità Ordinate', firstOrder: 'Primo Ordine', inStock: 'Disponibile', lowStock: 'Scorte Basse' }
  },
  inventory: { title: 'Inventario', description: 'Gestisci e monitora tutti gli articoli', stockLevels: 'Livelli di Stock', skus: 'SKU', searchPlaceholder: 'Cerca per nome articolo...', clearSearch: 'Cancella ricerca', totalItems: 'Totale Articoli', totalValue: 'Valore Totale', lowStockItems: 'Articoli a Basso Stock', warehouses: 'Magazzini', table: { sku: 'SKU', itemName: 'Nome Articolo', name: 'Nome', category: 'Categoria', warehouse: 'Magazzino', quantity: 'Quantità', quantityOnHand: 'Quantità Disponibile', reorderPoint: 'Punto di Riordino', unitCost: 'Costo Unitario', unitPrice: 'Prezzo Unitario', totalValue: 'Valore Totale', location: 'Posizione', status: 'Stato' } },
  orders: { title: 'Ordini', description: 'Visualizza e gestisci gli ordini clienti', allOrders: 'Tutti gli Ordini', totalOrders: 'Ordini Totali', totalRevenue: 'Ricavi Totali', avgOrderValue: 'Valore Medio Ordine', onTimeDelivery: 'Consegna Puntuale', itemsCount: '{count} articoli', quantity: 'Qtà', table: { orderNumber: 'Numero Ordine', orderId: 'ID Ordine', orderDate: 'Data Ordine', date: 'Data', customer: 'Cliente', category: 'Categoria', warehouse: 'Magazzino', items: 'Articoli', value: 'Valore', totalValue: 'Valore Totale', status: 'Stato', expectedDelivery: 'Consegna Prevista', actualDelivery: 'Consegna Effettiva' } },
  finance: { title: 'Dashboard Finanziaria', description: 'Monitora ricavi, costi e performance finanziaria', totalRevenue: 'Ricavi Totali', totalCosts: 'Costi Totali', netProfit: 'Utile Netto', avgOrderValue: 'Valore Medio Ordine', fromOrders: 'Da {count} ordini', costBreakdown: 'Approvvigionamento + Operativo + Personale + Spese Generali', margin: 'margine', perOrderRevenue: 'Ricavo per ordine', revenueVsCosts: { title: 'Ricavi vs Costi Mensili', revenue: 'Ricavi', costs: 'Costi Totali' }, monthlyCostFlow: { title: 'Flusso Costi Mensile', procurement: 'Approvvigionamento', operational: 'Operativo', labor: 'Personale', overhead: 'Spese Generali' }, categorySpending: { title: 'Spesa per Categoria', ofTotal: 'del totale' }, transactions: { title: 'Transazioni Recenti', id: 'ID', description: 'Descrizione', vendor: 'Fornitore', date: 'Data', amount: 'Importo' } },
  demand: { title: 'Previsione Domanda', description: 'Analizza le tendenze e le previsioni della domanda', increasingDemand: 'Domanda in Crescita', stableDemand: 'Domanda Stabile', decreasingDemand: 'Domanda in Calo', itemsCount: '{count} articoli', more: 'altri...', demandForecasts: 'Previsioni Domanda', table: { sku: 'SKU', itemName: 'Nome Articolo', currentDemand: 'Domanda Attuale', forecastedDemand: 'Domanda Prevista', change: 'Variazione', trend: 'Tendenza', period: 'Periodo' } },
  reports: { title: 'Report Performance', description: 'Metriche trimestrali e tendenze mensili', quarterlyPerformance: 'Performance Trimestrale', monthlyRevenueTrend: 'Tendenza Ricavi Mensile', monthOverMonth: 'Analisi Mese su Mese', totalRevenueYTD: 'Ricavi Totali (YTD)', avgMonthlyRevenue: 'Ricavi Medi Mensili', totalOrdersYTD: 'Ordini Totali (YTD)', bestQuarter: 'Trimestre Migliore', table: { quarter: 'Trimestre', totalOrders: 'Ordini Totali', totalRevenue: 'Ricavi Totali', avgOrderValue: 'Valore Medio Ordine', fulfillmentRate: 'Tasso Evasione', month: 'Mese', orders: 'Ordini', revenue: 'Ricavi', change: 'Variazione', growthRate: 'Tasso di Crescita' } },
  restocking: { title: 'Raccomandazioni Rifornimento', description: 'Raccomandazioni ordini basate su stock, previsioni e budget', budgetCeiling: 'Limite Budget', totalEstimatedSpend: 'Spesa Stimata Totale', remainingBudget: 'Budget Residuo', itemsCovered: 'Articoli Coperti', recommendedOrders: 'Ordini Consigliati', noRestocking: 'Nessun rifornimento necessario', noRestockingBudget: 'Nessun rifornimento nel budget attuale', allStocked: 'Tutti gli articoli hanno scorte adeguate.', partial: 'parziale', table: { priority: 'Priorità', sku: 'SKU', product: 'Prodotto', warehouse: 'Magazzino', onHand: 'Disponibile', reorderPoint: 'Punto Riordino', forecastedDemand: 'Domanda Prevista', recommendedQty: 'Qtà Consigliata', estimatedCost: 'Costo Stimato', totalEstimatedSpend: 'Spesa Stimata Totale' } },
  filters: { timePeriod: 'Periodo', location: 'Sede', category: 'Categoria', orderStatus: 'Stato Ordine', all: 'Tutti', allMonths: 'Tutti i Mesi' },
  status: { delivered: 'Consegnato', shipped: 'Spedito', processing: 'In Elaborazione', backordered: 'In Arretrato', inStock: 'Disponibile', lowStock: 'Scorte Basse', adequate: 'Adeguato' },
  trends: { increasing: 'crescente', stable: 'stabile', decreasing: 'decrescente' },
  priority: { high: 'Alta', medium: 'Media', low: 'Bassa' },
  categories: { circuitBoards: 'Schede Elettroniche', sensors: 'Sensori', actuators: 'Attuatori', controllers: 'Controllori', powerSupplies: 'Alimentatori' },
  spendingCategories: { rawMaterials: 'Materie Prime', components: 'Componenti', equipment: 'Attrezzature', consumables: 'Materiali di Consumo' },
  warehouses: { sanFrancisco: 'San Francisco', london: 'Londra', tokyo: 'Tokyo' },
  months: { jan: 'Gen', feb: 'Feb', mar: 'Mar', apr: 'Apr', may: 'Mag', jun: 'Giu', jul: 'Lug', aug: 'Ago', sep: 'Set', oct: 'Ott', nov: 'Nov', dec: 'Dic', january: 'Gennaio', february: 'Febbraio', march: 'Marzo', april: 'Aprile', june: 'Giugno', july: 'Luglio', august: 'Agosto', september: 'Settembre', october: 'Ottobre', november: 'Novembre', december: 'Dicembre' },
  profile: { profileDetails: 'Dettagli Profilo', myTasks: 'I Miei Compiti', logout: 'Disconnetti' },
  profileDetails: { title: 'Dettagli Profilo', email: 'Email', department: 'Reparto', location: 'Sede', phone: 'Telefono', joinDate: 'Data Assunzione', employeeId: 'ID Dipendente', close: 'Chiudi' },
  tasks: { title: 'I Miei Compiti', taskTitle: 'Titolo Compito', taskTitlePlaceholder: 'Inserisci titolo...', priority: 'Priorità', dueDate: 'Scadenza', addTask: 'Aggiungi Compito', noTasks: 'Nessun compito. Aggiungine uno sopra!' },
  language: { english: 'English', japanese: '日本語', selectLanguage: 'Seleziona Lingua' },
  common: { loading: 'Caricamento...', error: 'Errore', noData: 'Nessun dato disponibile', viewDetails: 'Visualizza Dettagli', close: 'Chiudi', save: 'Salva', cancel: 'Annulla', search: 'Cerca', filter: 'Filtra', export: 'Esporta', items: 'articoli' },
  productNames: {},
  customerNames: {}
}
